export interface IArticle {
    sku: string,
    name: string,
    salePrice: number,
    regularPrice: number,
    thumbnailImage: string,
    shortDescription: string,
    highResImage: string
}

// IMPORTANT VOUS NE DEVEZ PLUS UTILISER CES INFORMATIONS
export const articlesGlobeaux = [
  {
    "sku": "14611307",
    "name": "NE PAS UTILISE CES DONNEES VOUS DEVEZ CHANGER LE CODE POUR UTILISER LE SERVEUR",
    "shortDescription": "Ceci est juste pour avoir le code fonctionnel en attendant que vous le changer pour utiliser le serveur.",
    "customerRating": 4.08,
    "customerRatingCount": 49,
    "customerReviewCount": 49,
    "productUrl": "/fr-ca/produit/moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce/14611307",
    "currentRegion": null,
    "hideSavings": false,
    "hideSaleEndDate": false,
    "productType": null,
    "regularPrice": 999999999999999999.99,
    "salePrice": 999999999999999999.99,
    "saleEndDate": 1665125999000,
    "thumbnailImage": "https://cegep.fdtt.space/images/pasbon.png",
    "primaryParentCategoryId": null,
    "categoryName": "Moniteurs de jeu",
    "ehf": 6.0,
    "seoText": "moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce",
    "sellerId": null,
    "seller": null,
    "highResImage": "https://cegep.fdtt.space/images/pasbon.png",
    "altLangSeoText": null,
    "offerId": null,
    "priceUnit": "",
    "requiresAgeVerification": false,
    "isPriceEndsLabel": false,
    "hasPromotion": true,
    "isAdvertised": true,
    "isClearance": false,
    "isInStoreOnly": false,
    "isOnlineOnly": false,
    "isVisible": true,
    "isPreorderable": false,
    "isFrenchCompliant": true,
    "isMarketplace": false,
    "hasFrenchContent": false,
    "categoryIds": [
      "20001",
      "20367",
      "474835"
    ]
  },  {
    "sku": "14611307",
    "name": "NE PAS UTILISE CES DONNEES VOUS DEVEZ CHANGER LE CODE POUR UTILISER LE SERVEUR",
    "shortDescription": "Ceci est juste pour avoir le code fonctionnel en attendant que vous le changer pour utiliser le serveur.",
    "customerRating": 4.08,
    "customerRatingCount": 49,
    "customerReviewCount": 49,
    "productUrl": "/fr-ca/produit/moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce/14611307",
    "currentRegion": null,
    "hideSavings": false,
    "hideSaleEndDate": false,
    "productType": null,
    "regularPrice": 999999999999999999.99,
    "salePrice": 999999999999999999.99,
    "saleEndDate": 1665125999000,
    "thumbnailImage": "https://cegep.fdtt.space/images/pasbon.png",
    "primaryParentCategoryId": null,
    "categoryName": "Moniteurs de jeu",
    "ehf": 6.0,
    "seoText": "moniteur-jeu-del-incurve-va-hd-int-gtg-4-ms-freesync-75-hz-32-po-samsung-lc32r500-bleu-gris-fonce",
    "sellerId": null,
    "seller": null,
    "highResImage": "https://cegep.fdtt.space/images/pasbon.png",
    "altLangSeoText": null,
    "offerId": null,
    "priceUnit": "",
    "requiresAgeVerification": false,
    "isPriceEndsLabel": false,
    "hasPromotion": true,
    "isAdvertised": true,
    "isClearance": false,
    "isInStoreOnly": false,
    "isOnlineOnly": false,
    "isVisible": true,
    "isPreorderable": false,
    "isFrenchCompliant": true,
    "isMarketplace": false,
    "hasFrenchContent": false,
    "categoryIds": [
      "20001",
      "20367",
      "474835"
    ]
  }
];